# Generated by Django 5.1.6 on 2025-03-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='hide_answers',
            field=models.BooleanField(default=True, help_text='Скрывать правильные ответы до завершения теста'),
        ),
    ]
