# Generated by Django 5.1.6 on 2025-03-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_hide_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='Ограничение времени в минутах (0 - без ограничения)'),
        ),
    ]
