# Generated by Django 5.1.6 on 2025-03-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quiz_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='user_answers',
            field=models.JSONField(blank=True, help_text='Ответы пользователя в формате JSON', null=True),
        ),
    ]
